config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, controllers: { registrations: "user_registrations" }

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/landing_page'

  get 'static_pages/thank_you'

  root 'static_pages#index'

  post 'static_pages/thank_you'

  post 'payments/create'

  resources :orders, only: [:index, :show, :create, :destroy]

  resources :products do
    resources :comments
  end
  resources :users

  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Emily's Store</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= javascript_include_tag 'jquery.raty.js', "data-turbolinks-track" => false %>

    <%= csrf_meta_tags %>

  </head>

  <body data-spy="scroll" data-target=".navbar">

    <!-- navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div> <!-- end navbar-header -->

        <div class="navbar-collapse collapse">

          <%= form_tag("/products", method: "get", class: "nav navbar-nav form-inline") do %>
            <%= label_tag %>
            <%= text_field_tag(:q, nil, placeholder: 'Search', class: 'form-control search-text') %>
            <%= submit_tag("Submit", class: "btn btn-default search-btn") %>
          <% end %>

          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", static_pages_about_path %></li>
            <li><%= link_to "Contact", static_pages_contact_path %></li>
            <li><%= link_to "Products", products_path %>
            <li>
            <% if user_signed_in? %>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
            <% else %>
              <%= link_to('Login', new_user_session_path) %>
            <% end %>
          </ul>
        </div> <!-- end nav collapse -->
      </div> <!-- end container fluid -->
    </nav> <!-- end nav -->

    <% if notice %>
      <p id="notice" class="alert alert-info" button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true"></span></button>
      <strong><%= notice %></strong>
      </p>
    <% end %>

    <% if alert %>
      <p id="alert" class="alert alert-info" button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true"></span></button>
      <strong><%= notice %></strong>
      </p>
    <% end %>

  <%= yield %>

  <footer>
    &copy; 2017 Emily's Store
  </footer>

  </body>
</html>